package no.roedt.hypersys

enum class Hypersysverv(val id: Int) {
    Lagsleder(1),
    Fylkesleder(21),
    Nestleder(2),
    Styremedlem(5),
    StyremedlemMedKurs(34),
    StyrelederIKommuneorganisasjon(35),
    StyremedlemIKommuneOrganisasjon(36),
    Lyttekaptein(81),
    Oekonomiansvarleg(4),

    // Øvrige verv:
    Vara(6),
    Kontaktperson(12),
    Listekandidat(13),
    Regionsekretær(23),
    Medlemsvarsel(24),
    ValgkampsekretaerLokalt(29),
    Landsstyremedlem(31),
    VaraIKommuneorganisasjon(37),
    Organisasjonsutvalgmedlem(38),
    Foerstekandidat(39),
    EndrePersondata(42),
    Kommunestyrerepresentant(44),
    Fylkestingsrepresentant(45),
    Bydelsutvalgsrepresentant(46),
    VaraTilKommunestyret(47),
    VaraTilFylkestinget(49),
    VaraTilBydelsutvalget(50),
    OrganisasjonssekretaerLokaltAnsattForFylket(51),
    Valgkomitemedlem(52),
    Nominasjonskomitemedlem(57),
    FoerstekandidatTilStortinget(59),
    AndrekandidatTilStortinget(60),
    TredjekandidatTilStortinget(61),
    FjerdekandidatTilStortinget(62),
    FemtekandidatTilStortinget(63),
    Stortingslistekandidat(64),
    Samordningsstyremedlem(65),
    FoersteLSVara(69),
    UtvalgsmedlemLokalt(72),
    Komitemedlem(73),
    KumulertKandidat(74),
    Gruppeleder(75),
    FolkevalgtIKomiteRaadUtvalg(76),
    AndreLSVara(79)
}