quarkus.google.cloud.project-id=${projectId}
quarkus.rest-client.hypersys.url = ${hypersysBaseUrl}
projectId=qomon-hypersys
secretManagerProjectId=${projectId}
hypersysBaseUrl=https://raudt.hypersys.no/
google.cloud.service-account-location=.service-account.json
google.drive.rotmappenavn=Testmappe
%dev.hypersys.ekte=false
hypersys.ekte=true
qomonBaseUrl=https://incoming.qomon.app/
quarkus.rest-client.qomon.url = ${qomonBaseUrl}
