quarkus.google.cloud.project-id=${projectId}
quarkus.rest-client."no.roedt.hypersys.HypersysRestClient".url = ${hypersysBaseUrl}
projectId=qomon-hypersys
secretManagerProjectId=${projectId}
hypersysBaseUrl=https://raudt.hypersys.no/
google.cloud.service-account-location=.service-account.json
google.drive.rotmappenavn=Testmappe
%dev.hypersys.ekte=false
hypersys.ekte=true